// 急诊科常见诊断数据 - 500种
var diagnoses = [
  // 心血管系统
  {name:'急性心肌梗死',pinyin:'JXXGJS'},
  {name:'不稳定型心绞痛',pinyin:'BWDXJX'},
  {name:'心力衰竭',pinyin:'XLSJ'},
  {name:'高血压危象',pinyin:'GXYWX'},
  {name:'心律失常',pinyin:'XLSC'},
  {name:'室性心动过速',pinyin:'SXXDGS'},
  {name:'心房颤动',pinyin:'XFCD'},
  {name:'主动脉夹层',pinyin:'ZDMJC'},
  {name:'肺栓塞',pinyin:'FS'},
  {name:'深静脉血栓',pinyin:'SJMXS'},
  {name:'心脏骤停',pinyin:'XZT'},
  {name:'冠心病',pinyin:'GXB'},
  {name:'心肌炎',pinyin:'XJY'},
  
  // 呼吸系统
  {name:'急性上呼吸道感染',pinyin:'JXSHXgdgr'},
  {name:'肺炎',pinyin:'FY'},
  {name:'支气管哮喘',pinyin:'Zqgxc'},
  {name:'慢性阻塞性肺疾病',pinyin:'MXZXXfjb'},
  {name:'自发性气胸',pinyin:'ZFXqp'},
  {name:'肺结核',pinyin:'FJH'},
  {name:'咯血',pinyin:'KX'},
  {name:'呼吸困难',pinyin:'HXKN'},
  
  // 消化系统
  {name:'急性胃炎',pinyin:'JXWY'},
  {name:'胃溃疡',pinyin:'WKY'},
  {name:'上消化道出血',pinyin:'SXHDCX'},
  {name:'急性胰腺炎',pinyin:'JXYXY'},
  {name:'急性胆囊炎',pinyin:'JXDNY'},
  {name:'胆石症',pinyin:'DSZ'},
  {name:'肝硬化',pinyin:'GYH'},
  {name:'急性阑尾炎',pinyin:'JXLWY'},
  {name:'肠梗阻',pinyin:'CGZ'},
  {name:'腹膜炎',pinyin:'FMY'},
  {name:'腹股沟疝',pinyin:'FGGS'},
  {name:'腹泻',pinyin:'FX'},
  {name:'便秘',pinyin:'BM'},
  {name:'恶心呕吐',pinyin:'EXOT'},
  
  // 泌尿系统
  {name:'急性肾盂肾炎',pinyin:'JXSYSY'},
  {name:'肾结石',pinyin:'SJS'},
  {name:'输尿管结石',pinyin:'SNGJS'},
  {name:'尿路感染',pinyin:'NLGR'},
  {name:'急性尿潴留',pinyin:'JXNZL'},
  {name:'血尿',pinyin:'XN'},
  {name:'蛋白尿',pinyin:'DBN'},
  
  // 神经系统
  {name:'脑梗死',pinyin:'NGS'},
  {name:'脑出血',pinyin:'NCX'},
  {name:'短暂性脑缺血发作',pinyin:'DDXnqxfz'},
  {name:'癫痫',pinyin:'DX'},
  {name:'偏头痛',pinyin:'PTT'},
  {name:'面神经麻痹',pinyin:'MSJmb'},
  {name:'重症肌无力',pinyin:'ZJJwl'},
  {name:'脑震荡',pinyin:'NZD'},
  {name:'硬膜外血肿',pinyin:'YMWxz'},
  {name:'头晕',pinyin:'TY'},
  {name:'晕厥',pinyin:'YJ'},
  {name:'昏迷',pinyin:'HM'},
  
  // 内分泌系统
  {name:'糖尿病',pinyin:'TNB'},
  {name:'糖尿病酮症酸中毒',pinyin:'TNBtzsdz'},
  {name:'低血糖',pinyin:'DXT'},
  {name:'甲状腺功能亢进',pinyin:'ZJXgnkj'},
  {name:'高钾血症',pinyin:'GJxz'},
  {name:'低钾血症',pinyin:'DJxz'},
  {name:'代谢性酸中毒',pinyin:'DXxsdz'},
  
  // 血液系统
  {name:'缺铁性贫血',pinyin:'QTXpx'},
  {name:'白血病',pinyin:'BXB'},
  {name:'血小板减少性紫癜',pinyin:'XBjsxzd'},
  {name:'过敏性紫癜',pinyin:'GMXzd'},
  {name:'弥散性血管内凝血',pinyin:'MSXxgnx'},
  
  // 风湿免疫
  {name:'类风湿关节炎',pinyin:'LFSgjy'},
  {name:'系统性红斑狼疮',pinyin:'XTXhblc'},
  {name:'痛风',pinyin:'TF'},
  {name:'强直性脊柱炎',pinyin:'QZxjzy'},
  
  // 创伤
  {name:'颅脑外伤',pinyin:'LNWS'},
  {name:'颈椎骨折',pinyin:'JZgz'},
  {name:'胸椎骨折',pinyin:'XZgz'},
  {name:'腰椎骨折',pinyin:'YZgz'},
  {name:'肋骨骨折',pinyin:'LGgz'},
  {name:'骨盆骨折',pinyin:'GPgz'},
  {name:'股骨骨折',pinyin:'GGgz'},
  {name:'开放性骨折',pinyin:'KFXgz'},
  {name:'烧伤',pinyin:'SS'},
  {name:'冻伤',pinyin:'DS'},
  {name:'中暑',pinyin:'ZS'},
  {name:'溺水',pinyin:'NS'},
  {name:'多发伤',pinyin:'DFS'},
  
  // 中毒
  {name:'有机磷农药中毒',pinyin:'YJLndz'},
  {name:'急性酒精中毒',pinyin:'JXJJDZ'},
  {name:'一氧化碳中毒',pinyin:'YYHDZ'},
  {name:'食物中毒',pinyin:'SWDZ'},
  {name:'百草枯中毒',pinyin:'BCKDZ'},
  
  // 感染性疾病
  {name:'流感',pinyin:'LG'},
  {name:'病毒性肝炎',pinyin:'BDXgy'},
  {name:'破伤风',pinyin:'PSF'},
  {name:'败血症',pinyin:'BXZ'},
  {name:'脓毒症',pinyin:'NDZ'},
  {name:'急性扁桃体炎',pinyin:'JXBTTY'},
  
  // 产科
  {name:'先兆流产',pinyin:'XZLC'},
  {name:'异位妊娠',pinyin:'YWRS'},
  {name:'前置胎盘',pinyin:'QZTP'},
  {name:'产后出血',pinyin:'CHCX'},
  {name:'子痫',pinyin:'ZX'},
  {name:'早产',pinyin:'ZC'},
  
  // 儿科
  {name:'小儿肺炎',pinyin:'XEfy'},
  {name:'小儿腹泻',pinyin:'XEfx'},
  {name:'高热惊厥',pinyin:'GRju'},
  {name:'手足口病',pinyin:'SZKB'},
  
  // 眼科
  {name:'急性结膜炎',pinyin:'JXJMY'},
  {name:'青光眼',pinyin:'QGY'},
  {name:'视网膜脱离',pinyin:'SWMTC'},
  {name:'眼外伤',pinyin:'YWS'},
  {name:'麦粒肿',pinyin:'MLZ'},
  
  // 耳鼻喉科
  {name:'中耳炎',pinyin:'ZEY'},
  {name:'鼻出血',pinyin:'BCX'},
  {name:'急性会厌炎',pinyin:'JXHYY'},
  {name:'气管异物',pinyin:'QGYW'},
  
  // 皮肤科
  {name:'荨麻疹',pinyin:'XMZ'},
  {name:'药疹',pinyin:'YZ'},
  {name:'湿疹',pinyin:'SZ'},
  {name:'带状疱疹',pinyin:'DZPZ'},
  {name:'丹毒',pinyin:'DD'},
  {name:'过敏性休克',pinyin:'GMXxk'},
  
  // 心血管补充
  {name:'急性心肌梗死ST段抬高',pinyin:'JXXGJS'},
  {name:'急性冠脉综合征',pinyin:'JXGMzh'},
  {name:'心绞痛',pinyin:'XJT'},
  {name:'高血压3级',pinyin:'GXY3'},
  {name:'高血压2级',pinyin:'GXY2'},
  {name:'高血压1级',pinyin:'GXY1'},
  {name:'心房纤颤',pinyin:'XFXC'},
  {name:'室性早搏',pinyin:'SXZB'},
  {name:'房性早搏',pinyin:'FXZB'},
  {name:'房室传导阻滞',pinyin:'FSCDzz'},
  {name:'预激综合征',pinyin:'YJzh'},
  {name:'病态窦房结综合征',pinyin:'BTDfjzh'},
  {name:'心包积液',pinyin:'XBJY'},
  {name:'心肌病',pinyin:'XJB'},
  {name:'扩张型心肌病',pinyin:'KZXxb'},
  {name:'感染性心内膜炎',pinyin:'GRXxnmy'},
  {name:'心源性休克',pinyin:'XXXK'},
  
  // 呼吸系统补充
  {name:'社区获得性肺炎',pinyin:'SQHDXfy'},
  {name:'医院获得性肺炎',pinyin:'YYHDXfy'},
  {name:'支气管扩张症',pinyin:'Zqgkz'},
  {name:'肺脓肿',pinyin:'FNZ'},
  {name:'胸腔积液',pinyin:'XQJY'},
  {name:'结核性胸膜炎',pinyin:'JHXymy'},
  {name:'胸膜炎',pinyin:'XMY'},
  {name:'肺栓塞',pinyin:'FS'},
  {name:'急性呼吸衰竭',pinyin:'JXHxsf'},
  {name:'慢性呼吸衰竭',pinyin:'MXHxsf'},
  {name:'急性呼吸窘迫综合征',pinyin:'JXHxj'},
  {name:'支气管肺炎',pinyin:'Zqgfy'},
  {name:'大叶性肺炎',pinyin:'DYXfy'},
  {name:'间质性肺炎',pinyin:'JZXfy'},
  {name:'过敏性肺炎',pinyin:'GMXfy'},
  
  // 消化系统补充
  {name:'消化性溃疡',pinyin:'XHXky'},
  {name:'胃穿孔',pinyin:'WCK'},
  {name:'十二指肠溃疡',pinyin:'SEZCKY'},
  {name:'急性胃肠炎',pinyin:'JXW CY'},
  {name:'慢性胃炎',pinyin:'MXWY'},
  {name:'幽门梗阻',pinyin:'YMGZ'},
  {name:'急性肝衰竭',pinyin:'JXGSJ'},
  {name:'药物性肝损伤',pinyin:'YWXgss'},
  {name:'胆总管结石',pinyin:'DZGJS'},
  {name:'急性胆管炎',pinyin:'JXDGY'},
  {name:'胆道蛔虫病',pinyin:'DHCSb'},
  {name:'肠穿孔',pinyin:'CCK'},
  {name:'肠套叠',pinyin:'CTD'},
  {name:'急性肠炎',pinyin:'JXCY'},
  {name:'溃疡性结肠炎',pinyin:'KYXjcy'},
  {name:'克罗恩病',pinyin:'KLEb'},
  {name:'肠易激综合征',pinyin:'CYJzh'},
  {name:'胃食管反流病',pinyin:'WSGflb'},
  {name:'功能性消化不良',pinyin:'GNXxhbl'},
  {name:'消化道异物',pinyin:'XHDYW'},
  
  // 泌尿系统补充
  {name:'急性肾小球肾炎',pinyin:'JXSXQsy'},
  {name:'慢性肾小球肾炎',pinyin:'MXSXQsy'},
  {name:'肾病综合征',pinyin:'SBzh'},
  {name:'急性肾功能衰竭',pinyin:'JXSGNsf'},
  {name:'慢性肾功能衰竭',pinyin:'MXSGNsf'},
  {name:'膀胱结石',pinyin:'BGJS'},
  {name:'尿道结石',pinyin:'NDJS'},
  {name:'前列腺增生',pinyin:'QLXzs'},
  {name:'急性前列腺炎',pinyin:'JXQLXy'},
  {name:'睾丸扭转',pinyin:'GWNZ'},
  {name:'附睾炎',pinyin:'FGY'},
  {name:'肾积水',pinyin:'SJS'},
  {name:'尿道损伤',pinyin:'NDSS'},
  
  // 神经系统补充
  {name:'脑栓塞',pinyin:'NSS'},
  {name:'蛛网膜下腔出血',pinyin:'ZWMxcx'},
  {name:'硬膜下血肿',pinyin:'YMXxz'},
  {name:'脑挫裂伤',pinyin:'NCLS'},
  {name:'颅底骨折',pinyin:'LDgz'},
  {name:'脊髓损伤',pinyin:'JSss'},
  {name:'三叉神经痛',pinyin:'SCsjt'},
  {name:'面瘫',pinyin:'MT'},
  {name:'格林巴利综合征',pinyin:'GLBLzh'},
  {name:'重症肌无力',pinyin:'ZJJwl'},
  {name:'帕金森病',pinyin:'PJSb'},
  {name:'阿尔茨海默病',pinyin:'AECshm'},
  {name:'血管性痴呆',pinyin:'XGXcd'},
  {name:'脑膜炎',pinyin:'NMY'},
  {name:'脑炎',pinyin:'NY'},
  {name:'脑脓肿',pinyin:'NNZ'},
  {name:'颅内压增高',pinyin:'LNYzg'},
  
  // 内分泌补充
  {name:'1型糖尿病',pinyin:'1xtnb'},
  {name:'2型糖尿病',pinyin:'2xtnb'},
  {name:'糖尿病高渗状态',pinyin:'TNBGsz'},
  {name:'甲状腺危象',pinyin:'ZJXwx'},
  {name:'甲状腺功能减退',pinyin:'ZJXgnjt'},
  {name:'肾上腺危象',pinyin:'SSXwx'},
  {name:'嗜铬细胞瘤',pinyin:'SGXbl'},
  {name:'高钠血症',pinyin:'GNxz'},
  {name:'低钠血症',pinyin:'DNxz'},
  {name:'高钙血症',pinyin:'GJxz'},
  {name:'低钙血症',pinyin:'DJxz'},
  {name:'代谢性碱中毒',pinyin:'DXxjdz'},
  {name:'呼吸性酸中毒',pinyin:'HXxsdz'},
  {name:'呼吸性碱中毒',pinyin:'HXxjdz'},
  
  // 血液系统补充
  {name:'巨幼细胞贫血',pinyin:'JYXBpx'},
  {name:'再生障碍性贫血',pinyin:'ZSZApx'},
  {name:'溶血性贫血',pinyin:'RXpx'},
  {name:'血友病',pinyin:'XYB'},
  {name:'淋巴瘤',pinyin:'LBL'},
  {name:'多发性骨髓瘤',pinyin:'DFXgsl'},
  {name:'特发性血小板减少',pinyin:'TFXxbxjsj'},
  
  // 风湿免疫补充
  {name:'干燥综合征',pinyin:'GZzh'},
  {name:'多发性肌炎',pinyin:'DFXjy'},
  {name:'皮肌炎',pinyin:'PJY'},
  {name:'系统性硬化症',pinyin:'XTXyz'},
  {name:'血管炎',pinyin:'XGY'},
  {name:'骨关节炎',pinyin:'GGJY'},
  
  // 创伤补充
  {name:'锁骨骨折',pinyin:'SGgz'},
  {name:'肩关节脱位',pinyin:'JGJtw'},
  {name:'肘关节脱位',pinyin:'ZGJtw'},
  {name:'髋关节脱位',pinyin:'KGJtw'},
  {name:'踝关节骨折',pinyin:'HGJgz'},
  {name:'腕关节骨折',pinyin:'WGJgz'},
  {name:'胫骨骨折',pinyin:'JGgz'},
  {name:'腓骨骨折',pinyin:'FGgz'},
  {name:'跟骨骨折',pinyin:'GGgz'},
  {name:'脊柱骨折',pinyin:'JZgz'},
  {name:'骨盆骨折',pinyin:'GPgz'},
  {name:'软组织损伤',pinyin:'RZZss'},
  {name:'肌肉拉伤',pinyin:'JRls'},
  {name:'韧带损伤',pinyin:'RDss'},
  {name:'半月板损伤',pinyin:'BYBss'},
  {name:'颅脑损伤',pinyin:'LNSs'},
  {name:'脑挫伤',pinyin:'NCS'},
  {name:'硬脑膜外血肿',pinyin:'YNMWxz'},
  {name:'复合伤',pinyin:'FHS'},
  {name:'挤压伤',pinyin:'JYs'},
  {name:'挫伤',pinyin:'CS'},
  {name:'裂伤',pinyin:'LS'},
  {name:'刺伤',pinyin:'CS'},
  {name:'切割伤',pinyin:'QGs'},
  {name:'咬伤',pinyin:'Ys'},
  {name:'蜇伤',pinyin:'Zs'},
  {name:'烫伤',pinyin:'TS'},
  {name:'电击伤',pinyin:'DJs'},
  
  // 中毒补充
  {name:'镇静催眠药中毒',pinyin:'ZJCMYDZ'},
  {name:'阿片类中毒',pinyin:'APLdz'},
  {name:'抗精神病药中毒',pinyin:'KJSBDYDZ'},
  {name:'农药中毒',pinyin:'NYDZ'},
  {name:'灭鼠药中毒',pinyin:'MSYDZ'},
  {name:'煤气中毒',pinyin:'MQDZ'},
  {name:'天然气中毒',pinyin:'TRQDZ'},
  {name:'鱼胆中毒',pinyin:'YDDZ'},
  {name:'毒蕈中毒',pinyin:'DXDZ'},
  {name:'亚硝酸盐中毒',pinyin:'YXSYDZ'},
  {name:'毒蛇咬伤',pinyin:'DSYS'},
  {name:'蜂蜇伤',pinyin:'FZS'},
  {name:'狗咬伤',pinyin:'GYS'},
  {name:'猫抓病',pinyin:'MZB'},
  
  // 感染性疾病补充
  {name:'病毒性感冒',pinyin:'BDXgm'},
  {name:'咽炎',pinyin:'YY'},
  {name:'喉炎',pinyin:'HY'},
  {name:'支气管炎',pinyin:'Zqgy'},
  {name:'急性胃肠炎',pinyin:'JXW CY'},
  {name:'细菌性痢疾',pinyin:'XJXlj'},
  {name:'伤寒',pinyin:'SH'},
  {name:'副伤寒',pinyin:'FSH'},
  {name:'霍乱',pinyin:'HL'},
  {name:'登革热',pinyin:'DGR'},
  {name:'疟疾',pinyin:'NJ'},
  {name:'流行性腮腺炎',pinyin:'LXXsxy'},
  {name:'水痘',pinyin:'SD'},
  {name:'麻疹',pinyin:'MZ'},
  {name:'风疹',pinyin:'FZ'},
  {name:'猩红热',pinyin:'XHR'},
  {name:'流行性出血热',pinyin:'LXXcr'},
  {name:'结核性脑膜炎',pinyin:'JHXnmy'},
  {name:'化脓性脑膜炎',pinyin:'HLXnmy'},
  {name:'病毒性脑炎',pinyin:'BDXny'},
  {name:'狂犬病',pinyin:'KSB'},
  {name:'布鲁氏菌病',pinyin:'BLSjb'},
  {name:'恙虫病',pinyin:'YCb'},
  {name:'钩端螺旋体病',pinyin:'GDlxtb'},
  
  // 产科补充
  {name:'难免流产',pinyin:'NMLC'},
  {name:'不全流产',pinyin:'BQLC'},
  {name:'完全流产',pinyin:'WQLC'},
  {name:'稽留流产',pinyin:'JLLC'},
  {name:'葡萄胎',pinyin:'PTT'},
  {name:'胎盘早剥',pinyin:'TPZB'},
  {name:'子宫破裂',pinyin:'ZGPQ'},
  {name:'羊水栓塞',pinyin:'YSSS'},
  {name:'产褥感染',pinyin:'CRYgr'},
  {name:'妊娠高血压',pinyin:'RSGXY'},
  {name:'子痫前期',pinyin:'ZXQZ'},
  {name:'HELLP综合征',pinyin:'HELLPzh'},
  {name:'胎膜早破',pinyin:'TMZP'},
  {name:'胎儿窘迫',pinyin:'TEJP'},
  {name:'脐带脱垂',pinyin:'QDTC'},
  {name:'臀位',pinyin:'TW'},
  {name:'横位',pinyin:'HW'},
  {name:'宫缩乏力',pinyin:'GSFL'},
  {name:'会阴裂伤',pinyin:'HYLS'},
  {name:'新生儿窒息',pinyin:'XSESZX'},
  {name:'新生儿黄疸',pinyin:'XSEHD'},
  
  // 儿科补充
  {name:'轮状病毒肠炎',pinyin:'LZBDcy'},
  {name:'川崎病',pinyin:'CQb'},
  {name:'幼儿急疹',pinyin:'YEjz'},
  {name:'肠套叠',pinyin:'CTD'},
  {name:'肠痉挛',pinyin:'CJL'},
  {name:'维生素D缺乏性佝偻病',pinyin:'WSSDLQXglb'},
  {name:'先天性心脏病',pinyin:'XTXxzb'},
  {name:'法洛四联症',pinyin:'FLSLZ'},
  {name:'房间隔缺损',pinyin:'FJGqs'},
  {name:'室间隔缺损',pinyin:'SJGqs'},
  {name:'动脉导管未闭',pinyin:'DMGDWB'},
  
  // 眼科补充
  {name:'角膜炎',pinyin:'JMY'},
  {name:'急性闭角型青光眼',pinyin:'JXBJXqgy'},
  {name:'白内障',pinyin:'BNZ'},
  {name:'视神经炎',pinyin:'SSJY'},
  {name:'眼化学伤',pinyin:'YHXs'},
  {name:'眼穿通伤',pinyin:'YCTs'},
  
  // 耳鼻喉补充
  {name:'外耳道炎',pinyin:'WEDY'},
  {name:'急性中耳炎',pinyin:'JXZEY'},
  {name:'美尼尔病',pinyin:'MNEb'},
  {name:'突发性耳聋',pinyin:'TFXel'},
  {name:'鼻骨骨折',pinyin:'BGgz'},
  {name:'鼻中隔偏曲',pinyin:'BZGpq'},
  {name:'慢性鼻炎',pinyin:'MXBY'},
  {name:'过敏性鼻炎',pinyin:'GMXby'},
  {name:'鼻息肉',pinyin:'BXR'},
  {name:'急性喉炎',pinyin:'JXHY'},
  {name:'喉梗阻',pinyin:'HGZ'},
  {name:'食管异物',pinyin:'SGYW'},
  {name:'咽部异物',pinyin:'YBYW'},
  {name:'扁桃体周围脓肿',pinyin:'BTTZWnz'},
  
  // 皮肤科补充
  {name:'接触性皮炎',pinyin:'JCXpy'},
  {name:'脓疱疮',pinyin:'NPC'},
  {name:'蜂窝织炎',pinyin:'FWZY'},
  {name:'血管性水肿',pinyin:'XGXzs'},
  {name:'多形红斑',pinyin:'DXhb'},
  {name:'结节性红斑',pinyin:'JJXhb'},
  {name:'天疱疮',pinyin:'TPC'},
  {name:'银屑病',pinyin:'YXB'},
  
  // 牙科
  {name:'牙髓炎',pinyin:'YSY'},
  {name:'牙周炎',pinyin:'YZY'},
  {name:'智齿冠周炎',pinyin:'ZCGZY'},
  {name:'口腔溃疡',pinyin:'KQKY'},
  {name:'颌面部感染',pinyin:'HMBgr'},
  {name:'颌骨骨折',pinyin:'HGgz'},
  
  // 其他常见
  {name:'发热待查',pinyin:'FRDC'},
  {name:'腹痛待查',pinyin:'FTDC'},
  {name:'胸痛待查',pinyin:'XTDC'},
  {name:'头痛待查',pinyin:'TTDC'},
  {name:'休克',pinyin:'XK'},
  {name:'感染性休克',pinyin:'GRXxk'},
  {name:'失血性休克',pinyin:'SXXxk'},
  {name:'过敏性休克',pinyin:'GMXxk'},
  {name:'低血容量休克',pinyin:'DXRLxk'},
  {name:'心源性休克',pinyin:'XXXK'},
  {name:'脓毒性休克',pinyin:'NDxxk'},
  {name:'多器官功能衰竭',pinyin:'DQGgnsj'},
  {name:'电解质紊乱',pinyin:'DJZwl'},
  {name:'酸碱平衡失调',pinyin:'SSphtd'},
  {name:'脱水',pinyin:'TS'},
  {name:'虚脱',pinyin:'XT'},
  {name:'晕动病',pinyin:'YDb'},
  {name:'中暑高热',pinyin:'ZSGr'},
  {name:'热痉挛',pinyin:'RJL'},
  {name:'热衰竭',pinyin:'RSJ'},
  
  // 肿瘤相关
  {name:'肺癌',pinyin:'FA'},
  {name:'胃癌',pinyin:'WA'},
  {name:'肝癌',pinyin:'GA'},
  {name:'结肠癌',pinyin:'JCA'},
  {name:'直肠癌',pinyin:'ZCA'},
  {name:'胰腺癌',pinyin:'YXA'},
  {name:'食管癌',pinyin:'SGA'},
  {name:'膀胱癌',pinyin:'BGA'},
  {name:'肾癌',pinyin:'SA'},
  {name:'脑肿瘤',pinyin:'NZL'},
  {name:'骨肿瘤',pinyin:'GZL'},
  {name:'淋巴结转移',pinyin:'LBJzy'},
  
  // 心理相关
  {name:'焦虑症',pinyin:'JLZ'},
  {name:'抑郁症',pinyin:'YYZ'},
  {name:'癔症',pinyin:'YZ'},
  {name:'惊恐发作',pinyin:'JKFZ'},
  
  // 营养代谢
  {name:'营养不良',pinyin:'YYBL'},
  {name:'肥胖症',pinyin:'FPZ'},
  {name:'高脂血症',pinyin:'GZXZ'},
  {name:'高尿酸血症',pinyin:'GNsXZ'},
  {name:'痛风性关节炎',pinyin:'TFXgjy'},
  
  // 外科急腹症
  {name:'急性腹膜炎',pinyin:'JXFMY'},
  {name:'腹腔脓肿',pinyin:'FQNz'},
  {name:'肠扭转',pinyin:'CNZ'},
  {name:'肠系膜血管栓塞',pinyin:'CXmxgss'},
  {name:'嵌顿疝',pinyin:'QDS'},
  {name:'绞窄性肠梗阻',pinyin:'JSXcgz'},
  
  // 血管外科
  {name:'动脉瘤破裂',pinyin:'DMLpl'},
  {name:'动脉栓塞',pinyin:'DMss'},
  {name:'静脉曲张',pinyin:'JMQZ'},
  {name:'血栓闭塞性脉管炎',pinyin:'XSBXmgY'},
  {name:'雷诺综合征',pinyin:'LNzh'},
  
  // 泌尿外科补充
  {name:'肾挫伤',pinyin:'SCS'},
  {name:'膀胱破裂',pinyin:'BGpl'},
  {name:'尿道损伤',pinyin:'NDss'},
  {name:'睾丸扭转',pinyin:'GWNZ'},
  {name:'包皮嵌顿',pinyin:'BPQD'},
  
  // 骨科补充
  {name:'颈椎病',pinyin:'JZB'},
  {name:'腰椎间盘突出',pinyin:'YZjptc'},
  {name:'腰肌劳损',pinyin:'YJls'},
  {name:'肩周炎',pinyin:'JZY'},
  {name:'网球肘',pinyin:'WQZ'},
  {name:'腱鞘炎',pinyin:'JQY'},
  {name:'滑囊炎',pinyin:'HNY'},
  {name:'骨质疏松',pinyin:'GZss'},
  {name:'病理性骨折',pinyin:'BLXgz'},
  {name:'关节脱位',pinyin:'GJtw'},
  
  // 妇科补充
  {name:'痛经',pinyin:'TJ'},
  {name:'月经失调',pinyin:'YJST'},
  {name:'功能性子宫出血',pinyin:'GNXzgcx'},
  {name:'子宫肌瘤',pinyin:'ZGjl'},
  {name:'卵巢囊肿',pinyin:'LCnz'},
  {name:'盆腔炎',pinyin:'PQY'},
  {name:'阴道炎',pinyin:'YDY'},
  {name:'外阴炎',pinyin:'WYY'},
  
  // 小儿补充
  {name:'新生儿黄疸',pinyin:'XSEHD'},
  {name:'新生儿肺炎',pinyin:'XSEfy'},
  {name:'新生儿败血症',pinyin:'XSEbxz'},
  {name:'小儿惊厥',pinyin:'XEju'},
  {name:'营养性缺铁性贫血',pinyin:'YYXqtxpx'},
  {name:'维生素D缺乏',pinyin:'WSSDlqx'},
  {name:'鹅口疮',pinyin:'EKC'},
  {name:'尿布皮炎',pinyin:'NBpy'},
  
  // 眼科补充
  {name:'睑腺炎',pinyin:'JSY'},
  {name:'睑板腺囊肿',pinyin:'JGBxNZ'},
  {name:'结膜炎',pinyin:'JMY'},
  {name:'角膜溃疡',pinyin:'JMKY'},
  {name:'虹膜睫状体炎',pinyin:'HMJZTY'},
  {name:'视网膜中央静脉阻塞',pinyin:'SWMzYjmZS'},
  {name:'糖尿病视网膜病变',pinyin:'TNBswmbb'},
  
  // 耳鼻喉补充
  {name:'外耳道疖肿',pinyin:'WEDjz'},
  {name:'急性化脓性中耳炎',pinyin:'JXHLXzey'},
  {name:'慢性化脓性中耳炎',pinyin:'MXHLXzey'},
  {name:'鼻出血',pinyin:'BCX'},
  {name:'急性鼻窦炎',pinyin:'JXBDY'},
  {name:'慢性鼻窦炎',pinyin:'MXBDY'},
  {name:'鼻腔异物',pinyin:'BQYW'},
  {name:'急性咽炎',pinyin:'JXYY'},
  {name:'慢性咽炎',pinyin:'MXYY'},
  {name:'急性扁桃体周围脓肿',pinyin:'JXBTT'},
  {name:'扁桃体周围脓肿',pinyin:'BTTZWNZ'},
  {name:'急性会厌炎',pinyin:'JXHYY'},
  {name:'喉异物',pinyin:'HYW'},
  {name:'食管腐蚀伤',pinyin:'SGFSs'},
  
  // 口腔科
  {name:'牙龈炎',pinyin:'YYY'},
  {name:'牙周脓肿',pinyin:'YZNZ'},
  {name:'口腔颌面部间隙感染',pinyin:'KQHMBjxgr'},
  {name:'颞下颌关节紊乱',pinyin:'NXHGJwl'},
  {name:'口底蜂窝织炎',pinyin:'KDFWZY'},
  
  // 急诊常见症状
  {name:'发热',pinyin:'FR'},
  {name:'寒战',pinyin:'HZ'},
  {name:'乏力',pinyin:'FL'},
  {name:'消瘦',pinyin:'XS'},
  {name:'水肿',pinyin:'SZ'},
  {name:'黄疸',pinyin:'HD'},
  {name:'紫绀',pinyin:'ZG'},
  {name:'皮疹',pinyin:'PZ'},
  {name:'瘙痒',pinyin:'SY'},
  {name:'麻木',pinyin:'MM'},
  {name:'抽搐',pinyin:'CC'},
  {name:'震颤',pinyin:'ZC'},
  {name:'腹胀',pinyin:'FZ'},
  {name:'腹水',pinyin:'FS'},
  {name:'肝大',pinyin:'GD'},
  {name:'脾大',pinyin:'PD'},
  {name:'淋巴结肿大',pinyin:'LBJzd'},
  
  // 急诊操作相关
  {name:'过敏反应',pinyin:'GMfy'},
  {name:'输血反应',pinyin:'SXfy'},
  {name:'造影剂反应',pinyin:'ZYJfy'},
  {name:'药物不良反应',pinyin:'YWBLfy'},
  {name:'术后并发症',pinyin:'SHBFz'},
  {name:'切口感染',pinyin:'QKgr'},
  {name:'肺部感染',pinyin:'FBgr'},
  {name:'泌尿系感染',pinyin:'MNxgr'},
  {name:'导管相关感染',pinyin:'DGXGgr'},
  {name:'压疮',pinyin:'YC'},
  {name:'深静脉导管堵塞',pinyin:'Sjxgdg'},
  {name:'PICC导管堵塞',pinyin:'PICCDG'},
  {name:'术后疼痛',pinyin:'SHTT'},
  {name:'恶心',pinyin:'EX'},
  {name:'呕吐',pinyin:'OT'}
];

module.exports = diagnoses;
